"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import s from "../portal.module.css";
import b from "./booking.module.css";

const kurse = [
  { titel: "Erste-Hilfe-Ausbildung", ort: "Düsseldorf", datum: "18. August 2026 · 08:30–16:15", plaetze: "7 Plätze frei", preis: "59 €", bild: "/brands/personal-paramedic.png", tag: "9 UE · Führerschein & Betrieb" },
  { titel: "Erste Hilfe am Kind", ort: "Düsseldorf", datum: "22. August 2026 · 09:00–13:00", plaetze: "11 Plätze frei", preis: "49 €", bild: "/brands/personal-paramedic.png", tag: "Eltern, Familien & Betreuung" },
  { titel: "Erste-Hilfe-Fortbildung", ort: "Worbis", datum: "2. September 2026 · 08:30–16:15", plaetze: "14 Plätze frei", preis: "59 €", bild: "/brands/bww.jpeg", tag: "Betriebliche Ersthelfende" },
];

export default function Kurse() {
  const [buchung,setBuchung]=useState<(typeof kurse)[number]|null>(null);
  const [fahrschueler,setFahrschueler]=useState(false);
  const [meldung,setMeldung]=useState("");
  function demoMeldung(text:string){setMeldung(text);window.setTimeout(()=>setMeldung(""),4000)}
  return <main className={s.page} style={{"--accent":"#f20b7a","--dark":"#9c0750","--soft":"#fff0f7"} as React.CSSProperties}>
    <header className={s.header}><div className={s.brand}><Image src="/brands/personal-paramedic.png" alt="Personal Paramedic" width={160} height={50}/><div><strong>Kurswelt</strong><small>Einfach lernen. Sicher handeln.</small></div></div><nav className={s.nav}><Link href="/kurse">Kurse</Link><Link href="/affiliate">Empfehlen & verdienen</Link><Link href="/dozenten">Dozentenportal</Link><Link className={s.primary} href="/">Office Login</Link></nav></header>
    <section className={s.hero}><div><span className={s.eyebrow}><i/>OFFENE KURSE & INHOUSE-LEHRGÄNGE</span><h1>Erste Hilfe, die <em>wirklich ankommt.</em></h1><p>Passenden Termin auswählen, sicher online bezahlen und die Buchungsbestätigung sofort erhalten. Unternehmen können ihren individuellen Inhouse-Kurs direkt anfragen.</p><div className={s.actions}><a className={s.primary} href="#termine">Kurs finden</a><a href="#inhouse">Inhouse-Kurs anfragen</a></div></div><div className={s.heroVisual}><div className={s.heroCard}><small>NÄCHSTER KURS</small><h2>Erste-Hilfe-Ausbildung</h2><div className={s.miniRow}><span>◷</span><div><strong>18. August 2026</strong><small>08:30–16:15 Uhr</small></div><b>7 frei</b></div><div className={s.miniRow}><span>⌖</span><div><strong>Düsseldorf</strong><small>zentral & gut erreichbar</small></div></div><div className={s.miniRow}><span>✓</span><div><strong>Sofort bestätigt</strong><small>nach sicherer Stripe-Zahlung</small></div></div></div></div></section>
    <section className={s.section} id="termine"><div className={s.sectionHead}><div><h2>Aktuelle Kurstermine</h2><p>Alle Kurse mit freien Plätzen. Das Zertifikat wird nach bestätigter Teilnahme automatisch per E-Mail versendet.</p></div><button onClick={()=>demoMeldung("Filteransicht vorbereitet")}>Ort & Datum filtern</button></div><div className={s.cards}>{kurse.map(k=><article className={s.card} key={k.titel+k.datum}><div className={s.cardImage}><Image src={k.bild} alt="" width={500} height={250}/><span>{k.tag}</span></div><div className={s.cardBody}><h3>{k.titel}</h3><p>{k.datum}<br/>{k.ort}</p><div className={s.facts}><span>✓ Zertifikat</span><span>✓ QR-Check-in</span><span>{k.plaetze}</span></div><div className={s.cardFoot}><strong>{k.preis}</strong><button onClick={()=>{setBuchung(k);setFahrschueler(false)}}>Platz buchen</button></div></div></article>)}</div></section>
    <section className={s.section} id="inhouse"><div className={s.sectionHead}><div><h2>Inhouse-Kurs für Ihr Unternehmen</h2><p>Erste-Hilfe-Ausbildung mit bis zu 20 Personen ab 750 €. Eine Kostenübernahme durch Berufsgenossenschaft oder Unfallkasse wird direkt geprüft.</p></div></div><form className={s.form}><div className={s.field}><label>Unternehmen</label><input placeholder="Firmenname"/></div><div className={s.field}><label>Ansprechperson</label><input placeholder="Vor- und Nachname"/></div><div className={s.field}><label>Kursformat</label><select><option>Erste-Hilfe-Ausbildung (9 UE)</option><option>Erste-Hilfe-Fortbildung (9 UE)</option><option>Erste Hilfe in Bildungs- und Betreuungseinrichtungen</option><option>Anderes Kursformat</option></select></div><div className={s.field}><label>Wunschtermin</label><input type="date"/></div><div className={s.field}><label>Berufsgenossenschaft / Unfallkasse</label><input placeholder="z. B. VBG"/></div><div className={s.field}><label>Unternehmensnummer</label><input placeholder="15-stellige UNR.S"/></div><div className={`${s.field} ${s.wide}`}><label>Ort und Besonderheiten</label><input placeholder="Kursanschrift, Teilnehmerzahl und wichtige Hinweise"/></div><div className={`${s.field} ${s.wide} ${b.green}`}><strong>🌱 Gemeinsam nachhaltiger</strong><small>Optional können Sie für 2,50 € je Baum einen Beitrag auswählen.</small><label>Baumpaket</label><select><option>Kein Baum</option><option>1 Baum für den gesamten Lehrgang</option><option>10 Bäume</option><option>15 Bäume</option><option>20 Bäume</option><option>1 Baum pro Teilnehmer</option></select></div><button className={s.wide} type="button" onClick={()=>demoMeldung("Inhouse-Anfrage als Demo gespeichert – es wurden keine Daten versendet.")}>Unverbindliche Anfrage senden</button></form></section>
    {buchung&&<div className={b.backdrop} onMouseDown={()=>setBuchung(null)}><section className={b.modal} onMouseDown={e=>e.stopPropagation()}><header><div><small>PLATZ BUCHEN</small><h2>{buchung.titel}</h2><p>{buchung.datum} · {buchung.ort}</p></div><button onClick={()=>setBuchung(null)}>×</button></header><div className={s.form}><div className={s.field}><label>Vor- und Nachname</label><input placeholder="Teilnehmer/in"/></div><div className={s.field}><label>E-Mail</label><input type="email" placeholder="E-Mail-Adresse"/></div>{buchung.titel==="Erste-Hilfe-Ausbildung"&&<label className={`${b.consent} ${s.wide}`}><input type="checkbox" checked={fahrschueler} onChange={e=>setFahrschueler(e.target.checked)}/> Ich buche den Kurs für meinen Führerschein</label>}{fahrschueler&&<><div className={s.field}><label>Fahrschule</label><input placeholder="Name der Fahrschule"/></div><div className={s.field}><label>E-Mail der Fahrschule</label><input type="email" placeholder="kontakt@fahrschule.de"/></div><div className={`${s.field} ${s.wide}`}><label>Anschrift der Fahrschule</label><input placeholder="Straße, PLZ und Ort"/></div><label className={`${b.consent} ${s.wide}`}><input type="checkbox"/> Ich willige in die Übermittlung meines Zertifikats an die Fahrschule ein.</label></>}<label className={`${b.consent} ${s.wide}`}><input type="checkbox"/> 🌱 Für 2,50 € einen Baum zum Kurs beitragen</label><button className={s.wide} type="button" onClick={()=>{setBuchung(null);demoMeldung("Demo-Buchung vorbereitet – keine Zahlung oder Datenübertragung ausgelöst.")}}>Weiter zur Stripe-Zahlung (Demo)</button></div></section></div>}{meldung&&<div className={s.notice}>{meldung}</div>}
    <footer className={s.footer}><strong>Personal Paramedic & BWW</strong> · Sichere Buchung · Datenschutzkonforme Verarbeitung · Zertifikatsprüfung</footer>
  </main>
}
