"use client";

import Image from "next/image";
import Link from "next/link";
import { CSSProperties, FormEvent, useState } from "react";
import s from "../portal.module.css";

export default function Affiliate(){
  const [geprueft,setGeprueft]=useState(false);
  const pruefen=(event:FormEvent)=>{event.preventDefault();setGeprueft(true)};
  return <main className={s.page} style={{"--accent":"#0755aa","--dark":"#073b75","--soft":"#edf5ff"} as CSSProperties}>
    <header className={s.header}><div className={s.brand}><Image src="/brands/wippermann.png" alt="Wippermann" width={150} height={50}/><div><strong>Empfehlungsprogramm</strong><small>Gute Erfahrungen weitergeben</small></div></div><nav className={s.nav}><Link href="/kurse">Kurse</Link><Link href="/dozenten">Dozentenportal</Link><Link className={s.primary} href="/">Office</Link></nav></header>
    <section className={s.hero}><div><span className={s.eyebrow}><i/>NUR FÜR UNSERE ABSOLVENTEN</span><h1>Empfehlen, helfen und <em>5 % verdienen.</em></h1><p>Teile deine gute Kurserfahrung mit Freunden, Unternehmen, Schulen oder Vereinen. Neukunden sparen 5 % und du erhältst 5 % Provision.</p><div className={s.actions}><a className={s.primary} href="#registrieren">Jetzt registrieren</a><a href="#ablauf">So funktioniert es</a></div></div><div className={s.heroVisual}><div className={s.heroCard}><small>DEIN BEISPIEL</small><h2>Eine Empfehlung lohnt sich</h2><div className={s.miniRow}><span>↗</span><div><strong>Inhouse-Kurs vermittelt</strong><small>Kurswert 750 €</small></div><b>37,50 €</b></div><div className={s.miniRow}><span>♡</span><div><strong>Neukunde spart</strong><small>5 % Willkommensrabatt</small></div><b>37,50 €</b></div><div className={s.miniRow}><span>€</span><div><strong>Wöchentliche Auszahlung</strong><small>transparent im Portal</small></div></div></div></div></section>
    <section className={s.section} id="ablauf"><div className={s.sectionHead}><div><h2>Einfach und transparent</h2><p>Teilnehmen können volljährige Absolventinnen und Absolventen mit verifiziertem Kurszertifikat.</p></div></div><div className={s.steps}>{[["1","Zertifikat prüfen","Deine erfolgreiche Kursteilnahme wird über Zertifikatsnummer oder QR-Code bestätigt."],["2","Sicher registrieren","Identität, Volljährigkeit, Vertrag, Steuerangaben und Bankverbindung werden geprüft."],["3","Link teilen","Persönlichen Link oder QR-Code an Personen, Firmen, Schulen und Vereine weitergeben."],["4","Provision erhalten","Nach bezahlter Neukundenbuchung werden 5 % Guthaben wöchentlich ausgezahlt."]].map(x=><article className={s.step} key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <section className={s.section} id="registrieren"><div className={s.sectionHead}><div><h2>Teilnahme prüfen</h2><p>Ausweisdaten werden möglichst direkt durch einen spezialisierten Prüfpartner verarbeitet.</p></div></div><form className={s.form} onSubmit={pruefen}><div className={s.field}><label>Zertifikatsnummer</label><input required placeholder="z. B. P-2026-0001-08"/></div><div className={s.field}><label>Geburtsdatum</label><input required type="date"/></div><div className={s.field}><label>E-Mail-Adresse</label><input required type="email" placeholder="name@beispiel.de"/></div><div className={s.field}><label>Mobilnummer</label><input required placeholder="+49 …"/></div><button className={s.wide} type="submit">Berechtigung prüfen und Registrierung starten</button></form>{geprueft&&<div className={s.notice}><span>✓</span><div><strong>Demo-Prüfung erfolgreich vorbereitet</strong><p>Im Echtbetrieb folgen Identitätsprüfung, Volljährigkeitsnachweis und digitale Vertragsunterzeichnung. Provisionen gelten ausschließlich für echte Neukunden.</p></div></div>}</section>
    <footer className={s.footer}><strong>Wippermann Empfehlungsprogramm</strong> · Sichere Identitätsprüfung · Transparente Provisionen · Keine Belohnung für Bewertungen</footer>
  </main>
}
